ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of loop_sm_twoscalar'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'R2_GGHb = ', R2_GGHB
      WRITE(*,2) 'R2_GGHt = ', R2_GGHT
      WRITE(*,2) 'R2_GGeta0b = ', R2_GGETA0B
      WRITE(*,2) 'R2_GGeta0t = ', R2_GGETA0T
      WRITE(*,2) 'R2_GGiota0b = ', R2_GGIOTA0B
      WRITE(*,2) 'R2_GGiota0t = ', R2_GGIOTA0T
      WRITE(*,2) 'R2_GGHHb = ', R2_GGHHB
      WRITE(*,2) 'R2_GGHHt = ', R2_GGHHT
      WRITE(*,2) 'R2_GGHeta0b = ', R2_GGHETA0B
      WRITE(*,2) 'R2_GGHeta0t = ', R2_GGHETA0T
      WRITE(*,2) 'R2_GGHiota0b = ', R2_GGHIOTA0B
      WRITE(*,2) 'R2_GGHiota0t = ', R2_GGHIOTA0T
      WRITE(*,2) 'GC_5 = ', GC_5
      WRITE(*,2) 'GC_30 = ', GC_30
      WRITE(*,2) 'GC_HHeta0 = ', GC_HHETA0
      WRITE(*,2) 'GC_Heta0eta0 = ', GC_HETA0ETA0
      WRITE(*,2) 'GC_HHHH = ', GC_HHHH
      WRITE(*,2) 'GC_HHHeta0 = ', GC_HHHETA0
      WRITE(*,2) 'GC_HHHiota0 = ', GC_HHHIOTA0
      WRITE(*,2) 'GC_HHiota0 = ', GC_HHIOTA0
      WRITE(*,2) 'GC_Hiota0iota0 = ', GC_HIOTA0IOTA0
      WRITE(*,2) 'GC_Hiota0eta0 = ', GC_HIOTA0ETA0
      WRITE(*,2) 'GC_33 = ', GC_33
      WRITE(*,2) 'GC_933 = ', GC_933
      WRITE(*,2) 'GC_733 = ', GC_733
      WRITE(*,2) 'GC_37 = ', GC_37
      WRITE(*,2) 'GC_937 = ', GC_937
      WRITE(*,2) 'GC_737 = ', GC_737
