C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     1
C     
      SUBROUTINE MP_SSS1_2(S1, S3, COUP, M2, W2,S2)
      IMPLICIT NONE
      COMPLEX*32 CI
      PARAMETER (CI=(0Q0,1Q0))
      COMPLEX*32 S3(*)
      COMPLEX*32 S2(5)
      COMPLEX*32 S1(*)
      REAL*16 W2
      COMPLEX*32 P2(0:3)
      REAL*16 M2
      COMPLEX*32 DENOM
      COMPLEX*32 COUP
      S2(1) = +S1(1)+S3(1)
      S2(2) = +S1(2)+S3(2)
      S2(3) = +S1(3)+S3(3)
      S2(4) = +S1(4)+S3(4)
      P2(0) = -S2(1)
      P2(1) = -S2(2)
      P2(2) = -S2(3)
      P2(3) = -S2(4)
      DENOM = COUP/(P2(0)**2-P2(1)**2-P2(2)**2-P2(3)**2 - M2 * (M2 -CI
     $ * W2))
      S2(5)= DENOM*CI * S3(5)*S1(5)
      END


